### ISSUE TITLE
Error when entering help

### ISSUE THREAD

**Issue by pogopaule** [zakharykaplan/nvim-retrail#3] opened 2022-07-23 07:01 UTC
Similar to my [previous issue](https://github.com/zakharykaplan/nvim-retrail/issues/2) I get the following error when entering `:h nvim_set_keymap()`

```
Error detected while processing BufEnter Autocommands for "*":
Error executing lua callback: Vim:E803: ID not found: 4
stack traceback:
        [C]: in function 'matchdelete'
        ...site/pack/packer/start/nvim-retrail/lua/retrail/init.lua:92: in function 'matchdelete'
        ...site/pack/packer/start/nvim-retrail/lua/retrail/init.lua:38: in function <...site/pack/packer/start/nvim-retrail/lua/retrail/init.lua:34>
Error executing lua callback: Vim:E803: ID not found: 4
stack traceback:
        [C]: in function 'matchdelete'
        ...site/pack/packer/start/nvim-retrail/lua/retrail/init.lua:92: in function 'matchdelete'
        ...site/pack/packer/start/nvim-retrail/lua/retrail/init.lua:38: in function <...site/pack/packer/start/nvim-retrail/lua/retrail/init.lua:34>

```

Help is in my exclude list

```
require('retrail').setup {
  -- Highlight group to use for trailing whitespace.
  -- list all hlgroups with `:so $VIMRUNTIME/syntax/hitest.vim`
  hlgroup = 'Substitute',
  -- Enabled filetypes.
  filetype = {
    -- Strictly enable only on `include`ed filetypes. When false, only disabled
    -- on an `exclude`ed filetype.
    strict = false,
    -- Included filetype list.
    include = {},
    -- Excluded filetype list. Overrides `include` list.
    exclude = {
      '',
      'alpha',
      'help'
    },
  },
  -- Trim on write behaviour.
  trim = {
    -- Final blank (i.e. whitespace only) lines.
    blanklines = true,
  }
}
```

**Comment by kaplanz** [comment] 2022-07-24 01:55
Oof I thought I caught all the cases for this. Let me look more into the issue.

Thanks for providing your config!

**Comment by kaplanz** [comment] 2022-07-24 17:00
I don't seem to be able to recreate the issue using your config. Could you provide me with a minimal config/steps that cause the issue?

**Comment by pogopaule** [comment] 2022-07-24 17:38
<del> I managed to narrow down the probable cause. A postfix snippet not appearing in the list only happens when my [tmux source](https://github.com/pogopaule/dotfiles/blob/master/nvim/lua/pogopaule/plugins/cmp.lua#L25) is active. So either the tmux source itself is the problem or that fact that the tmux source provides many many completion entries. </del>

<del> But what is not explained by the tmux source is the fact that I need to write out the full postfix snippet name to make it appear as a suggestion. This seems to be a problem independent of the "tmux source problem". The problem only disappears if `luasnip` is my only source. <del/>

<del> Example: The snippet's name is `.log` </del>

With only `.lo` this happens
![image](https://user-images.githubusercontent.com/576949/180659545-325e94b8-afeb-4b10-8b85-1f734ab1a664.png)


With `.log`
![image](https://user-images.githubusercontent.com/576949/180659512-8a00783e-7409-4a84-a09a-3d02c80b6fad.png)

Now I disable all sources expect for `luasnip` and `.l` is sufficient to make the snippet appear.
![image](https://user-images.githubusercontent.com/576949/180659802-6ddd030c-4545-4f24-8dc8-54884e3136b1.png)


<del> @zakharykaplan: I edited this comment a couple of times. This is my final version in case you have seen it before my last edit. </del>

**Comment by kaplanz** [comment] 2022-07-24 18:28
I see. Could you also clarify the exact steps that cause the `E803` issue to appear when calling `:h nvim_set_keymap()`? (I assume any `:help` command should do it as well.)

I've tried adding the tmux source and editing filetypes that have postfix snippets (in this case, Rust files with the snippets `.ref`, `.rc`, etc.), however, invoking help afterwards doesn't seem to trigger the issue for me.

EDIT: I can't seem to reproduce it either after using other completion sources that provide many entries.

**Comment by pogopaule** [comment] 2022-07-24 19:18
Ahhhh omg, lol! I was responding to another issue and managed to mix it up with this one. :see_no_evil: :see_no_evil:
The comment was not meant for you but the other issue. So sorry!! Please ignore the previous comment.

I'll try to pin down the cause for this issue tomorrow.

**Comment by kaplanz** [comment] 2022-07-24 19:42
Haha no worries!

**Comment by kaplanz** [comment] 2022-07-26 12:48
This should be definitively fixed now.

My previous approaches at fixing this have been optimistically trying to prevent `matchdelete` from failing due to the match not existing, however it seems that Neovim will occasionally arbitrarily clear matches (or at least has some weird undocumented behaviours, possibly related to popups).

I've decided to just use `pcall` to just always ignore this error, as such, I am closing this issue.

@pogopaule Thanks for the feedback and help in documenting this!

**Closed as completed by kaplanz** 2022-07-26 12:48 UTC

**Comment by pogopaule** [comment] 2022-07-26 14:51
LGTM too. Thank you for fixing it!
